#!/usr/bin/env python3
"""
WSL2 Service Startup Script Generator

Generates a bash script that checks if a systemd user service is running,
starts it if not, and keeps WSL alive with `exec sleep infinity`.

Usage:
    python create_startup_script.py --service hermes-gateway [--distro Ubuntu-22.04] [--output /home/user/start_hermes.sh]
"""

import argparse
import os
import sys


TEMPLATE = '''#!/bin/bash
# Auto-generated startup script for {service} on WSL2
# Generated by wsl2-service-keeper skill

# Check if service is already running
if systemctl --user is-active --quiet {service}.service 2>/dev/null; then
    echo "{service} already running, skipping start."
else
    echo "Starting {service}..."
    systemctl --user start {service}.service
fi

# Keep WSL alive - DO NOT REMOVE
# Without this, WSL may consider itself idle and stop the distribution
exec sleep infinity
'''


def main():
    parser = argparse.ArgumentParser(
        description="Generate a WSL2 startup script for a systemd user service"
    )
    parser.add_argument(
        "--service", required=True,
        help="Name of the systemd user service (without .service suffix)"
    )
    parser.add_argument(
        "--output", default=None,
        help="Output path for the script (default: ./start_<service>.sh)"
    )
    args = parser.parse_args()

    output = args.output or f"./start_{args.service}.sh"
    content = TEMPLATE.format(service=args.service)

    with open(output, "w", newline="\n") as f:
        f.write(content)

    # Make executable on Unix-like systems
    if sys.platform != "win32":
        os.chmod(output, 0o755)

    print(f"✅ Startup script created: {output}")
    print()
    print("⚠️  Important next steps:")
    print(f"  1. Copy this script to your WSL distribution")
    print(f"  2. Fix line endings if edited on Windows:  sed -i 's/\\r$//' {output}")
    print(f"  3. Make executable:  chmod +x {output}")
    print(f"  4. Register a Windows Scheduled Task to run:  wsl -d <distro> -- bash {output}")


if __name__ == "__main__":
    main()
