#!/usr/bin/env python3
"""
WSL2 Auto-Start Scheduled Task Registration Script

Generates a PowerShell script that registers a Windows Scheduled Task
to auto-start a WSL2 service on login using S4U (Service for User) mode.

Usage:
    python register_autostart.py --task-name Hermes-WSL-AutoStart --distro Ubuntu-22.04 --script-path /home/user/start_hermes.sh --user QL\\yuqil

The generated PowerShell script should be run as Administrator.
"""

import argparse
import sys


TEMPLATE = '''
# Auto-generated Scheduled Task registration script for WSL2 auto-start
# Generated by wsl2-service-keeper skill
# ⚠️ Run this script as Administrator!

$taskName = "{task_name}"
$distro = "{distro}"
$scriptPath = "{script_path}"
$user = "{user}"

# Verify running as admin
if (-NOT ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {{
    Write-Error "This script must be run as Administrator!"
    exit 1
}}

# Check if WSL is available
$wslPath = Get-Command wsl.exe -ErrorAction SilentlyContinue
if (-not $wslPath) {{
    Write-Error "wsl.exe not found. Is WSL installed?"
    exit 1
}}

# Verify the distro exists
$distroList = wsl.exe -l -q 2>$null
if ($distroList -notcontains $distro) {{
    Write-Warning "Distro '$distro' not found. Available distros:"
    wsl.exe -l -q
    Write-Error "Please specify a valid distro name."
    exit 1
}}

# Create the task
$principal = New-ScheduledTaskPrincipal -UserId $user -LogonType S4U -RunLevel Highest
$settings = New-ScheduledTaskSettingsSet `
    -AllowStartIfOnBatteries `
    -DontStopIfGoingOnBatteries `
    -ExecutionTimeLimit 'PT0S' `
    -RestartCount 3 `
    -RestartInterval (New-TimeSpan -Minutes 1)
$action = New-ScheduledTaskAction -Execute "wsl.exe" -Argument "-d $distro -- bash $scriptPath"
$trigger = New-ScheduledTaskTrigger -AtLogon

# Remove existing task if present
Unregister-ScheduledTask -TaskName $taskName -Confirm:$false -ErrorAction SilentlyContinue

# Register the task
Register-ScheduledTask `
    -TaskName $taskName `
    -Principal $principal `
    -Action $action `
    -Trigger $trigger `
    -Settings $settings `
    -Force

Write-Host "✅ Scheduled task '$taskName' registered successfully!" -ForegroundColor Green
Write-Host ""
Write-Host "Task details:"
Get-ScheduledTask -TaskName $taskName | Format-List TaskName, State, Principal
Write-Host ""
Write-Host "To test manually:  Start-ScheduledTask -TaskName '$taskName'"
Write-Host "To verify service:  wsl -d $distro -- systemctl --user status <service>"
'''


def main():
    parser = argparse.ArgumentParser(
        description="Generate a PowerShell script to register a WSL2 auto-start Scheduled Task"
    )
    parser.add_argument(
        "--task-name", required=True,
        help="Name for the Windows Scheduled Task (e.g., Hermes-WSL-AutoStart)"
    )
    parser.add_argument(
        "--distro", required=True,
        help="WSL distribution name (e.g., Ubuntu-22.04)"
    )
    parser.add_argument(
        "--script-path", required=True,
        help="Path to the startup script inside WSL (e.g., /home/user/start_hermes.sh)"
    )
    parser.add_argument(
        "--user", required=True,
        help="Windows user account in DOMAIN\\username format (e.g., QL\\yuqil)"
    )
    parser.add_argument(
        "--output", default=None,
        help="Output path for the PowerShell script (default: ./Register-<task-name>.ps1)"
    )
    args = parser.parse_args()

    output = args.output or f"./Register-{args.task_name}.ps1"
    content = TEMPLATE.format(
        task_name=args.task_name,
        distro=args.distro,
        script_path=args.script_path,
        user=args.user,
    )

    with open(output, "w", encoding="utf-8", newline="\r\n") as f:
        f.write(content)

    print(f"✅ PowerShell script created: {output}")
    print()
    print("⚠️  To use this script:")
    print(f"  1. Run PowerShell as Administrator")
    print(f"  2. Execute:  .\\{output}")
    print(f"  3. Test with:  Start-ScheduledTask -TaskName '{args.task_name}'")


if __name__ == "__main__":
    main()
